auth/urls.py
from django.urls import path
from .views import (
    login_view,
    logout_view,
)

app_name = 'auth'

urlpatterns = [
    path('login/',login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

dashboard_upprogram_students/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from auth.views import HomeView
from students import views as student_views
from students.views import list_students
from evaluations import views as evaluations_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth.urls', namespace='auth')),
    re_path('', include('evaluations.urls')),
    re_path('', include('students.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', HomeView, name='home'),
    path('students/', list_students, name='students'),
    path('create-student', student_views.create_student, name='create'),
    path('delete-student', student_views.delete_student, name='delete'),
    path('update-student/<pk>/', student_views.update_student, name='update'),
    path('evaluations', evaluations_views.list_evaluation, name='evaluations'),
    path('create-evaluation', evaluations_views.create_evaluation, name='create_evaluation'),
    path('delete-evaluation', evaluations_views.delete_evaluation, name='delete_evaluation'),
    path('update-evaluation/<pk>', evaluations_views.update_evaluation, name='update_evaluation'),
    path('create-rubro', evaluations_views.create_rubro, name='create_rubro'),
    path('delete-rubro', evaluations_views.delete_rubro, name='delete_rubro' )
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>


    <!-- Custom js & css -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Up! | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

templates/navbar.html
{% url 'auth:logout' as path_to_logout %}
{% url 'students' as path_to_students%}
{% url 'evaluations' as path_to_evaluations%}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="{{path_to_students}}">Up! Program</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav" style="justify-content: space-between;">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{path_to_students}}">Students</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{path_to_evaluations}}">Evaluations</a>
            </li>
        </ul>
        
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if request.user.is_authenticated %}
                    <a class="nav-link" href="{{path_to_logout}}">Logout</a>
                {% endif %}
            </li>
        </ul>
        
    </div>
</nav>